GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzAzNDksImV4cCI6MTcxNjAzMzk0OSwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.BUPji_jXHsBXt0XO5wHXYzv2hfa4pL7MtLo5w_3t4J0

###Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Refresh token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzAzNDksImV4cCI6MTc0NzU4Nzk0OSwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.ridxC6MxjUZBL5CHlU8zZ9wMacHQgTE68Y4ZaQeJelc"
}

###Logout route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzAzNDksImV4cCI6MTc0NzU4Nzk0OSwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.ridxC6MxjUZBL5CHlU8zZ9wMacHQgTE68Y4ZaQeJelc"
}