GET http://localhost:9999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwNTEyMDEsImV4cCI6MTcxNjA1MTIyMSwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5OTk5In0.Vf63RXjW22wPqWQDLJsFcUt-WWYI-TeQPFrUqAta51U

###Login route
POST http://localhost:9999/auth/login
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Register route
POST http://localhost:9999/auth/register
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Refresh token route
POST http://localhost:9999/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwNTEyMDEsImV4cCI6MTc0NzYwODgwMSwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5OTk5In0.rLfU7zT_lzp_yEWTcbc277KafBesanxE5K-cYlg4EV0"
}

###Logout route
DELETE http://localhost:9999/auth/logout
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTc0NzU4OTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.o0Z54KZ-ilFZjqnufX-WI2ohPQjFKzC2Vp_3AZrO0Jw"
}

###Logout all route
DELETE http://localhost:9999/auth/logout-all
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTc0NzU4OTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.o0Z54KZ-ilFZjqnufX-WI2ohPQjFKzC2Vp_3AZrO0Jw"
}