GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTcxNjAzNTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.6rreny9bbzNFrNgFgZcE7rh2uYfytgBQxiyKzJiSuHI

###Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "minhdevtree@gmail.com",
    "password": "123456"
}

###Refresh token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTc0NzU4OTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.o0Z54KZ-ilFZjqnufX-WI2ohPQjFKzC2Vp_3AZrO0Jw"
}

###Logout route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTc0NzU4OTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.o0Z54KZ-ilFZjqnufX-WI2ohPQjFKzC2Vp_3AZrO0Jw"
}

###Logout all route
DELETE http://localhost:3000/auth/logout-all
Content-Type: application/json

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYwMzIzNTYsImV4cCI6MTc0NzU4OTk1NiwiYXVkIjoiNjY0ODhiNDVlMzZiMDRlOGZkZmM3MjE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.o0Z54KZ-ilFZjqnufX-WI2ohPQjFKzC2Vp_3AZrO0Jw"
}